### ISSUE TITLE
[Bug] - keybinds and other data don't save

### ISSUE THREAD

**Issue by glitch128** [cohenerickson/Velocity#10]
I have found that multiple things that should save between reloads don't. the things that I have found that don't save are as follows:
- keybinds
- bookmarks
- tabs
- UI toggles(bookmarks bar)

**Comment by cohenerickson** [comment]
I am aware of the tabs not saving and I have yet to implement a way to store the keybinds, the others I will have to do some investigating.

**Comment by cohenerickson** [comment]
Fixed in [v1.3.0](https://github.com/cohenerickson/Velocity/releases/tag/v1.3.0)
