### ISSUE TITLE
ipaddr.js throws error when attempting to load webpage.

### ISSUE THREAD

**Issue by SevenworksDev** [cohenerickson/Velocity#25]
Using the commands on the README on Node.js v20.0.0 works but trying to fetch a webpage from Velocity returns an error in the ipaddr.js package. I don't know if its in error in Velocity or the ipaddr.js package but I'm gonna ask here first.

Error:
throw new Error('ipaddr: the address has neither IPv6 nor IPv4 format');

Error: ipaddr: the address has neither IPv6 nor IPv4 format

**Comment by cohenerickson** [comment]
Nodejs 20 is not considered a stable version of node, try downgrading to the latest stable version (18.16.0) and see if the error persists.

**Comment by cohenerickson** [comment]
@SevenworksDev bump

**Comment by SevenworksDev** [comment]
Still doesn't work on Node 18/14.

**Comment by cohenerickson** [comment]
I'm unable to reproduce this error, can you provide some more system information and exact steps to reproduce it?

**Comment by SevenworksDev** [comment]
System I use is Windows 10 Pro (32-bit)

**Comment by Knox248** [comment]
What’s the url

**Comment by SevenworksDev** [comment]
> What’s the url for the proxy

http://127.0.0.1:4200

**Comment by fruvs** [comment]
im getting the same error but im running it on localhost:3000

`max@penguin:~/Velocity$ npm start

> velocity@1.3.0 start
> node scripts/server.js

Velocity listening on http://localhost:3000/
/home/max/Velocity/node_modules/ipaddr.js/lib/ipaddr.js:929
            throw new Error('ipaddr: the address has neither IPv6 nor IPv4 format');
            ^

Error: ipaddr: the address has neither IPv6 nor IPv4 format
    at ipaddr.parse (/home/max/Velocity/node_modules/ipaddr.js/lib/ipaddr.js:929:19)
    at GetAddrInfoReqWrap.callback (/home/max/Velocity/node_modules/@tomphttp/bare-server-node/dist/createServer.js:29:46)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:131:8)

Node.js v20.1.0`

**Comment by cohenerickson** [comment]
This is an issue with NodeJS v20
