### ISSUE TITLE
Static version

### ISSUE THREAD

**Issue by coolgamerkid332** [cohenerickson/Velocity#27]
Is there going to be a static version of this soon, so I can deploy to vercel/netlify/github pages?
I prefer this method as I can specify my own bare server and host it where it wont get deleted.

**Comment by cohenerickson** [comment]
In order to build static assets, run `npm run build`. The output should be in `dist/public` and you can host those files anywhere you want. In order to change the bare server host, that will be located in `dist/public/uv/uv.config.js`.

**Comment by coolgamerkid332** [comment]
oh okay, thank you for the clarification!
