### ISSUE TITLE
Bookmarklet Support

### ISSUE THREAD

**Issue by CoolBro129** [cohenerickson/Velocity#30]
Bookmarklet support would allow the user to execute arbitrary javascript on any website.

**Comment by glitch128** [comment]
it's planned

**Comment by cohenerickson** [comment]
The groundwork for extension support has already been implemented, the main limiting factor right now is the lack of general popup support. I have been quite busy and probably will be for another few weeks but once things slow down for me I will work on implementing them.

**Comment by cohenerickson** [comment]
It should now be possible for one to create bookmarklets, simply bookmark any page with Ctrl+D, edit the bookmark from the context menu and change the URL to be a `javascript:` URI.
