### ISSUE TITLE
[Bug]: Velocity not loading when using it inside of an Ultraviolet Instance

### ISSUE THREAD

**Issue by Notplayingallday383** [cohenerickson/Velocity#35]
### What Happened

Hi, I'm experiencing an issue lately where Velocity simply does not load inside of an ultraviolet instance such as being Proxied in terbium and simple is just a white screen.
![image](https://github.com/cohenerickson/Velocity/assets/72810050/43d49b13-010d-4388-91df-3dbcc895b158)

### Expected Behavior

```text
That velocity would work correctly unless it specificly doesn't work inside of a UV instance
```

### Steps to Reproduce

```text
Go to any UV Website (ex. nubulaproxy.io)
Go to velocity.radon.games (defualt url)
It displays a white screen
```

### Other Information

```text
Browser: Microsoft Edge 114.0.1823.43 (Stable x64)
OS: Microsoft Windows 11 22H2

Version of Ultraviolet (my own radon proxy site) Ultraviolet v1.0.8-beta
```

### Checklist

- [X] I have read and followed the contributing guidelines

**Comment by cohenerickson** [comment]
This would be an issue with Ultraviolet itself, using Velocity inside of Ultraviolet also defeats the purpose of using Velocity as a proxy.
