### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jscreator123** [cohenerickson/Velocity#36]
### What Happened

error while running.

### Expected Behavior

```text
to work
```

### Steps to Reproduce

```text
idk
```

### Other Information

```text
error while running.
```

### Checklist

- [X] I have read and followed the contributing guidelines

**Comment by jscreator123** [comment]
sorry lol was bored just there is a error when i did the steps you asked me to do

**Comment by cohenerickson** [comment]
Thanks for following every step on how to NOT make an issue.
