### ISSUE TITLE
[Bug]: npm not installing

### ISSUE THREAD

**Issue by DoxrGitHub** [cohenerickson/Velocity#39]
### What Happened

used npm i (self host) and it didn't work, seems to be babel, it says somehting about syslinks

### Expected Behavior

```text
npm sucessfully installing everythging
```

### Steps to Reproduce

```text
git clone and
`npm i` command should be enough
```

### Other Information

```text
using a phone, termux, not rooted.
```

### Checklist

- [X] I have read and followed the contributing guidelines

**Comment by maxicode2** [comment]
What is the console output you receive when you run `npm i`?

**Comment by DoxrGitHub** [comment]
@maxicode2 it's 
```
.../termux/DoxrTunnels $ npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'velocity@1.3.0',
npm WARN EBADENGINE required: { node: '18.x' },
npm WARN EBADENGINE current: { node: 'v20.2.0', npm: '9.6.6' }
npm WARN EBADENGINE }
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../@babel/parser/bin/babel-parser.js
npm ERR! dest /storage/emulated/0/termux/DoxrTunnels/node_modules/.bin/parser
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../@babel/parser/bin/babel-parser.js' -> '/storage/emulated/0/termux/DoxrTunnels/node_modules/.bin/parser'
npm ERR! [Error: EPERM: operation not permitted, symlink '../@babel/parser/bin/babel-parser.js' -> '/storage/emulated/0/termux/DoxrTunnels/node_modules/.bin/parser'] {
npm ERR! errno: -1,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'symlink',
npm ERR! path: '../@babel/parser/bin/babel-parser.js',
npm ERR! dest: '/storage/emulated/0/termux/DoxrTunnels/node_modules/.bin/parser'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2023-08-20T19_03_50_770Z-debug-0.log
.../termux/DoxrTunnels $
```

**Comment by cohenerickson** [comment]
You need to be running Node v18 not Node v20.

**Comment by DoxrGitHub** [comment]
how do I downgrade @cohenerickson

**Comment by Nailington** [comment]
How did you install npm?

**Comment by cohenerickson** [comment]
> how do I downgrade @cohenerickson

Use NVM

https://github.com/nvm-sh/nvm

**Comment by DoxrGitHub** [comment]
oh ok
ty

> install npm
i used apt

**Comment by DoxrGitHub** [comment]
NVM doesn't work. Any ideas?

**Comment by maxicode2** [comment]
Once again, what console output did you receive?

**Comment by DoxrGitHub** [comment]
it says my specified version doesn't exist (found it from https://nodejs.org/en/download/releases), sorry for bothering you btw

**Comment by maxicode2** [comment]
What is the result of running `node --version` in your terminal? If it doesn't start with v18, you most likely forgot to include the proper version of node in your $PATH.

**Comment by DoxrGitHub** [comment]
v20.2.0, $PATH is [android-dir]/com.termux/files/usr/bin which I don't think NVM was configured to use hence why I couldn't install nvm.

**Comment by maxicode2** [comment]
Make sure you followed [this guide](https://github.com/nvm-sh/nvm#:~:text=To%20install%20or,%3A%20.%20~/.profile) for properly installing NVM.

**Comment by DoxrGitHub** [comment]
Yeah I did, I found out that both nvm and Termux try to use PREFIX and so it will never work together. I'm unable to install nodejs with curl/wget, I must use apt/pkg. If you have any ideas I'd like to hear it because I simply don't think this is possible. *I've tried `n`, doesn't work.

**Comment by Nailington** [comment]
What are your source lists/repos that apt are using

using apt provides the LTS versions of node in my case, but I'm on (K)ubuntu

**Comment by romanovj** [comment]
> Yeah I did, I found out that both nvm and Termux try to use PREFIX

actually no
https://github.com/termux/termux-app/issues/3469#issuecomment-1598238480
