### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by T3M1N4L** [cohenerickson/Velocity#5]
I know I might be bothering you, so sorry, but..

I have a question concrening Velocity
I have been trying to create a custom version/theme of it

https://6c836537-d4e9-460a-9fb8-5c5d86cda5d4.id.repl.co/
So like, I want to change the colors
But I don't know where the css/typescript is?
can you send me the directory
which I can edit these colors?

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/108430379/224596867-e7b8455d-59a3-4d75-b0cc-7dd865cd8ea4.PNG">

Disclaimer: This is for personal use, and Credit will be given
Working on doing that

**Comment by GreenyDEV** [comment]
Velocity uses TailwindCSS, which means all of it is inline. Since tabs come from JS, it's likely somewhere in a script.
<img width="898" alt="image" src="https://user-images.githubusercontent.com/81369743/224849821-76c3f11c-8e05-4ef5-8493-d6cc6f3c9977.png">

**Comment by cohenerickson** [comment]
Right now velocity doesn’t have any way built-in way to customize a theme, in the future a theme API is planned to add support for chrome/firefox themes.

**Comment by cohenerickson** [comment]
Implemented in [v1.3.0](https://github.com/cohenerickson/Velocity/releases/tag/v1.3.0)
