### ISSUE TITLE
where is the logo

### ISSUE THREAD

**Issue by uhidontkno** [cohenerickson/Velocity#53]
its gone
![image](https://github.com/cohenerickson/Velocity/assets/86028086/528ddf34-2fa7-4584-ad03-88808f75b138)

**Comment by rifting** [comment]
This was fixed in https://github.com/cohenerickson/Velocity/commit/5cd010c3e13be7255f28d6d27d9857ec47db9df0. Are you sure your version of velocity is the latest version? Do you have any extensions that could be interfering?

**Comment by uhidontkno** [comment]
> This was fixed in [5cd010c](https://github.com/cohenerickson/Velocity/commit/5cd010c3e13be7255f28d6d27d9857ec47db9df0). Are you sure your version of velocity is the latest version? Do you have any extensions that could be interfering?

Perhaps the official link is outdated

**Comment by proudparrot2** [comment]
Yes, I'm on https://velocity.radon.games and I can confirm it's gone
![CleanShot 2024-07-08 at 16 36 55](https://github.com/cohenerickson/Velocity/assets/71939973/4036520b-dd48-4619-8626-4fd4d1c80813)

**Comment by uhidontkno** [comment]
guys the velocity logo disappeared

**Comment by uhidontkno** [comment]
shits just an empty div

**Comment by rifting** [comment]
> > This was fixed in [5cd010c](https://github.com/cohenerickson/Velocity/commit/5cd010c3e13be7255f28d6d27d9857ec47db9df0). Are you sure your version of velocity is the latest version? Do you have any extensions that could be interfering?
> 
> Perhaps the official link is outdated

Yes, the official link has been outdated for a while. This is a non-issue

**Comment by uhidontkno** [comment]
> > > This was fixed in [5cd010c](https://github.com/cohenerickson/Velocity/commit/5cd010c3e13be7255f28d6d27d9857ec47db9df0). Are you sure your version of velocity is the latest version? Do you have any extensions that could be interfering?
> > 
> > Perhaps the official link is outdated
> 
> Yes, the official link has been outdated for a while. This is a non-issue

I will close, please update the official link to prevent this from hsppening sgain
