### ISSUE TITLE
[Feature request] - Use PWA to created windowed experience

### ISSUE THREAD

**Issue by glitch128** [cohenerickson/Velocity#7]
Making Velocity a PWA would make the user experience more like an actual browser. The experimental [Window Controls Overlay API](https://developer.mozilla.org/en-US/docs/Web/API/Window_Controls_Overlay_API) could also be implemented to remove the title bar making an even more seamless UI.

**Comment by cohenerickson** [comment]
Yes, this is definitely on the list of things to do, I have had some issues with PWA's in the past when using Vite as a bundler, but I will see what can be done about that.

**Comment by glitch128** [comment]
a bundler? I was just thinking of creating a manifest.json file and linking it to the index.html file, since you already have a service worker registered

**Comment by cohenerickson** [comment]
I am going to limit this to just PWA support as of now due to the style overhauls that would be required to implement Window Controls Overlay API however I will keep it in mind.

**Comment by cohenerickson** [comment]
Added in [v1.3.0](https://github.com/cohenerickson/Velocity/releases/tag/v1.3.0)

**Comment by glitch128** [comment]
hey, change this line in the manifest from 
`"start_url": "/index.html"`
to this
` "start_url": "/"`
because all I get is a white screen when it opens from index.html
